version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME: youssef
    #   - MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
    networks:
      - gols-net
  backend:
    build: ./backend
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #   args: 
    #     some-arg: 1
    ports:
      - '80:80'
    networks:
      - gols-net
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    networks:
      - gols-net
    stdin_open: true
    tty: true # -it
    depends_on:
      - backend

volumes:
  data:
  logs:
networks:
  gols-net:
    driver: bridge
    
